name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  test-code:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        # install version with reigster json schema function
        # install curator packages
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Sage-Bionetworks/synapsePythonClient@486a9fc457d4fae8b54c9823fc195c3b38ae3eb9
          pip install pytest inflection networkx pandarallel pandas rdflib

      - name: Run Tests
        env:
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
        run: |
          python -m pytest tests -v


  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/container-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        env:
          ORG_NAME: dpetest
          SCHEMA_DIR: /schema_dir
          FIX_SCHEMA_NAME: "true"
        run: |
          docker run \
            -v $(pwd)/tests/schema_dir:/schema_dir \
            --env ORG_NAME="${{ env.ORG_NAME }}" \
            --env SCHEMA_DIR="${{ env.SCHEMA_DIR }}" \
            --env FIX_SCHEMA_NAME="${{ env.FIX_SCHEMA_NAME }}" \
            --env SYNAPSE_AUTH_TOKEN="${{ secrets.SYNAPSE_AUTH_TOKEN }}" \
            --rm ${{ env.TEST_TAG }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action
        id: register
        uses: ./
        with:
          org-name: dpetest
          schema-dir: tests/schema_dir
          synapse-auth-token: ${{ secrets.SYNAPSE_AUTH_TOKEN }}


  test-workflow:
    name: GitHub Workflow Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Generate JSON Schemas
        id: generate
        uses: Sage-Bionetworks-Actions/generate-jsonschema@main
        with:
          data-model-source: ./tests/data_model.csv
          data-model-labels: "display_label"

      - name: Register JSON Schemas
        id: register
        uses: ./
        with:
          org-name: dpetest
          fix-schema-name: "true"
          schema-dir: ${{ steps.generate.outputs.schemas}}
          synapse-auth-token: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
